version: '3.2'

services:
  db:
    image: postgres:16
    restart: always
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
  app:
    image: nextcloud:28
    restart: always
    networks:
      - nextcloud_network
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html/data
    depends_on:
      - db

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db

  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nextcloud

networks:
  nextcloud_network:
