version: '3.2'

services:
  db:
    image: postgres:16
    restart: always
    networks:
      - nextcloud_network
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud:28
    restart: always
    networks:
      - nextcloud_network
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=db
    depends_on:
      - db

networks:
  nextcloud_network:











# version: '3'

# services:
#   db:
#     image: postgres:16
#     restart: always
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=nextcloud
#       - POSTGRES_USER=nextcloud
#       - POSTGRES_PASSWORD=nextcloud
#     # networks:
#     #   - nextcloud_network

#   redis:
#     image: redis:7
#     restart: always
#     # networks:
#     #   - nextcloud_network

#   app:
#     image: nextcloud:28
#     ports:
#       - 8080:80
#     depends_on:
#       - db
#     volumes:
#       - nextcloud_data:/var/www/html
#     # environment:
#     #   - POSTGRES_DB=nextcloud
#     #   - POSTGRES_USER=nextcloud
#     #   - POSTGRES_PASSWORD=nextcloud
#     #   - POSTGRES_HOST=db
#     #   - REDIS_HOST=redis
#     restart: always
#     # networks:
#     #   - nextcloud_network

# volumes:
#   db_data:
#   nextcloud_data:

# networks:
#   nextcloud_network: