version: '3.2'

services:
  db:
    image: postgres:16
    restart: always
    networks:
      - nextcloud_network
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud:28
    restart: always
    networks:
      - nextcloud_network
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    # environment:
    #   - POSTGRES_DB=nextcloud
    #   - POSTGRES_USER=nextcloud
    #   - POSTGRES_PASSWORD=nextcloud
    #   - POSTGRES_HOST=db
    depends_on:
      - db

networks:
  nextcloud_network:
